log4j2 implemented / public interfaces / used @Param
TomashevskiiVladimirSolvd/navigator pull request #17
Opened 2023-07-10 22:49 UTC by AndrewTchaikovsky

1) I applied log4j2 throughout the project. We had both log4j1 and log4j2 in our pom.xml which caused my project on Windows to break. We had both log4j1 and log4j2 dependencies added in Maven. In fact, we only used log4j1 everywhere in the project and maintained a config file for it. I removed the old config, added a new one for log4j2 (it is different now) and re-wrote the methods to work with log4j2 (the methods are also different).
2) I explicitly added "public" to all interfaced as advised by mentor in last class;
3) I added @Param to setWayPoints method.

2023-07-11 22:18 UTC, remynewton approved these changes
LGTM!

2023-07-12 00:17 UTC, TomashevskiiVladimirSolvd approved these changes
LGTM as well)

2023-07-12 00:51 UTC, nislam2664 requested changes
Questionable error on RouteMapper.xml?

2023-07-12 00:51 UTC, nislam2664 commented on src/main/resources/mapper/RouteMapper.xml
> +        INSERT INTO waypoints (points_id, routes_id) VALUES (#{point.id}, #{route.id})
think this should be points.id and routes.id (missing 's') if we're referencing the tables

2023-07-12 01:40 UTC, nislam2664 approved these changes
Ignore previous request. I misread the code.

2023-07-12 08:34 UTC, merged