created DAOs
TomashevskiiVladimirSolvd/navigator pull request #3
Opened 2023-07-03 16:18 UTC by nislam2664

2023-07-03 16:47 UTC, TomashevskiiVladimirSolvd approved these changes
Looks good.In the next time please use your personal branch.

2023-07-03 17:51 UTC, remynewton requested changes
Should we perhaps add an update for Route and a delete for Point?

2023-07-03 22:46 UTC, remynewton approved these changes

2023-07-04 00:22 UTC, chiemeliecoder commented
It looks good

2023-07-04 01:48 UTC, chiemeliecoder approved these changes

2023-07-04 01:48 UTC, merged